### ISSUE TITLE
Where we can get this Datasets?

### ISSUE THREAD

**Issue by JoelEmbiiddddd** [underdoc-wang/EMS-Pred-ICDE-21#1]
Hello ,  I'm a graduate student who has just touched this subject and I am very interested in your work.

So I want to know where i can get this datasets in this paper so that i can make some innovation on this bassic

**Comment by underdoc-wang** [comment]
Hi there, thanks for your interest. However, we are not allowed to open the dataset for this paper. Maybe you can refer to the other paper on a similar task: https://github.com/underdoc-wang/STC-GNN, for which we made the data public.
